spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    enabled: false

zuul:
  sensitiveHeaders: Authorization
  routes:
    board:
      url: http://localhost:8081
      stripPrefix: false
    users:
      url: http://localhost:8082
      stripPrefix: false
    comments:
      url: http://localhost:8081
      stripPrefix: false
    alarm:
      url: http://localhost:8083
      stripPrefix: false