zuul:
  routes:
      board:
        url: http://localhost:8080
        stripPrefix: false
      users:
        url: http://localhost:8082
        stripPrefix: false
      comments:
        url: http://localhost:8080
        stripPrefix: false
      alarm:
        url: http://localhost:8081
        stripPrefix: false

